export const TOGGLE_EDIT_FORM = 'TOGGLE_EDIT_FORM';
export const TOGGLE_NEW_FORM = 'TOGGLE_NEW_FORM';
export const SELECTED_QUIZ = 'SELECTED_QUIZ';
export const DESELECTED_QUIZ = 'DESELECTED_QUIZ';
export const TOGGLE_RESPONSE = 'TOGGLE_RESPONSE';